name = "my-app"
compatibility_date = "2024-09-29"
pages_build_output_dir = "./dist/cloudflare"
compatibility_flags = ["nodejs_compat"]


# https://developers.cloudflare.com/d1/build-with-d1/local-development/#develop-locally-with-pages
[[d1_databases]]
binding = "DB"                             # Should match preview_database_id
database_name = "<your-database-name>"
database_id = "<your-database-id>"         # wrangler d1 info YOUR_DATABASE_NAME
preview_database_id = "DB"                 # Required for Pages local development
migrations_dir = "src/database/migrations"
